"""ID document upload endpoints — accepts uploads via secure link token."""

import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Query, status
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.guest import Guest
from app.models.session import Session
from app.services import link_service, storage_service
from app.state_machine import StateMachine
from app.state_machine.states import State
from app.state_machine.transitions import get_required_action

logger = logging.getLogger(__name__)

router = APIRouter(tags=["id-upload"])

# Template directory
_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "templates"
_templates = Jinja2Templates(directory=str(_TEMPLATE_DIR))


@router.get(
    "/id-upload/{token}",
    summary="Serve the ID upload form page",
    response_class=HTMLResponse,
)
async def get_upload_page(
    token: str,
    return_url: str | None = Query(default=None),
) -> HTMLResponse:
    """Render the ID document upload form for a secure link token.

    The token was previously generated by the agent and sent to the guest.
    This endpoint serves the HTML upload page. If the token payload
    contains a return_url, it takes precedence over the query parameter.
    """
    payload = link_service.verify_link(token)
    if payload is None or payload.get("purpose") != "id_upload":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired upload link",
        )

    # Token-embedded return_url takes precedence over query param
    effective_return_url = payload.get("return_url") or return_url

    # Read and return the upload page HTML
    upload_page = _TEMPLATE_DIR / "id_upload_page.html"
    if not upload_page.exists():
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Upload page template not found",
        )
    html_content = upload_page.read_text()

    # Inject return_url into the page as a JS variable
    if effective_return_url:
        return_url_script = (
            f'<script>var returnUrl = "{effective_return_url}";</script>'
        )
        html_content = html_content.replace(
            "</head>", f"{return_url_script}\n</head>"
        )
    else:
        html_content = html_content.replace(
            "</head>", '<script>var returnUrl = null;</script>\n</head>'
        )

    return HTMLResponse(content=html_content)


@router.post(
    "/id-upload/{token}",
    summary="Accept ID document upload",
)
async def upload_id_document(
    token: str,
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Accept an ID document upload from a secure link.

    Validates the token, saves the file, records the upload
    against the guest's record, and advances the state machine.
    """
    # Verify token
    payload = link_service.verify_link(token)
    if payload is None or payload.get("purpose") != "id_upload":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired upload link",
        )

    session_id = payload["session_id"]

    # Load session
    result = await db.execute(
        select(Session).where(Session.id == session_id)
    )
    session = result.scalar_one_or_none()
    if session is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found",
        )

    # Read and validate file
    file_data = await file.read()
    filename = file.filename or "unknown"

    try:
        file_path = await storage_service.save_file(
            file_data=file_data,
            filename=f"{session_id}_{filename}",
            subfolder="ids",
        )
    except storage_service.FileTooLargeError as exc:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=str(exc),
        )
    except storage_service.InvalidExtensionError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        )
    except storage_service.StorageServiceError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"File storage error: {exc}",
        )

    # Update guest record with document path
    result = await db.execute(
        select(Guest).where(Guest.id == session.guest_id)
    )
    guest = result.scalar_one_or_none()
    if guest is not None:
        guest.id_document_path = file_path
        guest.id_verified = True
        await db.flush()

    # Advance state machine: ID_VERIFY_PENDING → INCIDENTAL_PROTECTION_PENDING
    new_state = None
    try:
        current_state = State(session.current_state)
        if current_state == State.ID_VERIFY_PENDING:
            sm = StateMachine(db_session=db, session_id=session.id)
            await sm.advance("upload_id", guest_response="ID uploaded via secure link")
            await db.flush()
            # Reload session to get the new state
            await db.refresh(session)
            new_state = session.current_state
            logger.info(
                "State advanced after ID upload: session=%s -> %s",
                session_id,
                new_state,
            )
    except Exception as exc:
        logger.warning(
            "Could not advance state after ID upload: %s", exc
        )

    # Push WebSocket state_update so the chat widget knows immediately
    if new_state is not None:
        try:
            from app.api.websocket import manager as ws_manager

            await ws_manager.send_state_update(
                session_id,
                {
                    "current_state": new_state,
                    "required_action": get_required_action(State(new_state)),
                    "message": "ID document uploaded successfully",
                },
            )
        except Exception as exc:
            logger.warning(
                "Failed to push WS state_update after ID upload: %s", exc
            )

    logger.info(
        "ID document uploaded for session %s: %s", session_id, file_path
    )

    return {
        "message": "ID document uploaded successfully",
        "file_path": file_path,
        "verified": True,
    }
